name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@9975af7d6b957abec9ee9646effa3fb3b82c5314
      with:
        cxServer: sast.daniel.com
        cxUsername: daniel.gerbi@company.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer
